apiVersion: v1
kind: Service
metadata:
  name: prometheus-external
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external 
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip  
  labels:
    app: prometheus
  namespace: monitoring
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 9090
  selector:
    statefulset.kubernetes.io/pod-name: prometheus-0
   