# apiVersion: apps/v1
# kind: StatefuleSet
# metadata:
#   name: prometheus
#   labels:
#     app: prometheus
#   namespace: monitoring
# spec:
#   selector:
#     matchLabels:
#       app: prometheus
#   serviceName: prometheus
#   template:
#     metadata:
#       labels:
#         app: prometheus
#     spec:
#       securityContext:
#         fsGroup: 2000
#       containers:
#       - name: prometheus
#         image: quay.io/prometheus/prometheus
#         args:
#         - --config.file=/etc/prometheus/prometheus.yaml
#         - --storage.tsdb.path=/data
#         ports:
#         - containerPort: 9090
#         volumeMonunts:
#         - name: prometheus-config
#           mountPath: /etc/prometheus
#         - name: prometheus-data
#           mountPath: /data
#       volumes:
#       - name: prometheus-config
#         configMap:
#           name: prometheus-config
#     volumeClaimTemplates:
#     - metadata:
#         name: prometheus-data
#       spec:
#         accessModes:
#         - ReadwriteOnce
#         resources:
#           requests:
#             storage: 10Gi

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
  labels:
    app: prometheus
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: prometheus
  serviceName: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      securityContext:
        fsGroup: 2000
      containers:
      - name: prometheus
        image: quay.io/prometheus/prometheus
        args:
        - --config.file=/etc/prometheus/prometheus.yaml
        - --storage.tsdb.path=/data
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus
        - name: prometheus-data
          mountPath: /data
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config
  volumeClaimTemplates:
  - metadata:
      name: prometheus-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi