# apiVersion: v1
# kind: Service
# metadata:
#   name: prometheus
#   lables:
#     app: prometheus
#   namespace: monitoring
# spec:
#   ports:
#   - port: 9090
#   clusterIP: None
#   selector:
#     app: prometheus

apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
  namespace: monitoring
spec:
  ports:
  - port: 9090
  clusterIP: None
  selector:
    app: prometheus