apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

availabilityZones:
- ap-southeast-2a
- ap-southeast-2c

metadata:
  name: eks1
  region: ap-southeast-2
  version: '1.25'
  tags:
    env: eks1

iam:
  withOIDC: true
  
    ##iamIdentityMappings:
    ##- arn: arn:aws:iam::866477832211:user/user1
    ##groups:
    ## - system:masters
    #username: user1
    # noDuplicateARNs: true
    #- account: "866477832211"

vpc:
  cidr: 10.40.0.0/16
  clusterEndpoints:
    privateAccess: true
    publicAccess: true

addons:
- name: vpc-cni
  version: v1.12.5-eksbuild.2
  configurationValues: "{\"env\":{\"ENABLE_PREFIX_DELEGATION\":\"true\", \"ENABLE_POD_ENI\":\"true\", \"POD_SECURITY_GROUP_ENFORCING_MODE\":\"standard\"}}"
  resolveConflicts: overwrite

managedNodeGroups:
- name: default
  desiredCapacity: 2
  minSize: 2
  maxSize: 4
  instanceType: t3.medium
  privateNetworking: true
  releaseVersion: 1.25.6-20230304
  labels:
    "role": "worker"
