apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::866477832211:role/eksctl-eks1-nodegroup-default-NodeInstanceRole-VDQSEbw0HNkf
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::866477832211:role/user1
      username: console-iam-role
  mapUsers: |
    - groups:
      - system:masters
      userarn: arn:aws:iam::866477832211:user/user1
      username: console-iam-user
kind: ConfigMap
metadata:
  creationTimestamp: "2023-11-08T04:57:02Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "3466"
  uid: 805fa013-1b44-4f9b-856a-05eed0873b1c
