cat <<EOF | kubectl replace --force -f -
apiVersion: v1
kind: Pod
metadata:
  name: aws-cli
  namespace: logging
spec:
  serviceAccountName: aws-for-fluent-bit
  containers:
  - name: aws-cli
    image: amazon/aws-cli
    command: ["sleep", "3600"]
EOF