apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-for-fluent-bit
  namespace: logging
  labels:
    helm.sh/chart: aws-for-fluent-bit-0.1.31
    app.kubernetes.io/name: aws-for-fluent-bit
    app.kubernetes.io/instance: aws-for-fluent-bit
    app.kubernetes.io/version: "2.31.12.20231011"
    app.kubernetes.io/managed-by: Helm
data:
  flb_log_cw: "true"
  fluent-bit.conf: |
    [SERVICE]
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_PORT    2020
        Health_Check On 
        HC_Errors_Count 5 
        HC_Retry_Failure_Count 5 
        HC_Period 5 
        
        Parsers_File /fluent-bit/parsers/parsers.conf
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        DB                /var/log/flb_kube.db
        multiline.parser  docker, cri
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
        Exclude_Path      /var/log/containers/*_kubecost_*.log,/var/log/containers/*_logging_*.log
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        Merge_Log           On
        Merge_Log_Key       data
        Keep_Log            On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
        Buffer_Size         32k
    [OUTPUT]
        Name                      s3
        Match                     *
        bucket                    eks1-fluentbit-logging
        region                    ap-southeast-2
        s3_key_format             /eks1/$TAG[5]/%Y-%m-%d/%H/%M/$TAG[4]
        upload_timeout            1m
        content_type              txt
        s3_key_format_tag_delimiters ._
    [OUTPUT]
        Name cloudwatch_logs
        Match *
        region ap-southeast-2
        log_group_name fallback-group
        log_stream_prefix fallback-stream
        auto_create_group true
        log_group_template fluentbit-cloudwatch/namespace/$kubernetes['namespace_name']
        log_stream_template $kubernetes['pod_name'].$kubernetes['container_name']
    