apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::866477832211:role/eks1-fluentbit-loggroup
  name: aws-for-fluent-bit
  namespace: logging
  labels:
    helm.sh/chart: aws-for-fluent-bit-0.1.31
    app.kubernetes.io/name: aws-for-fluent-bit
    app.kubernetes.io/instance: aws-for-fluent-bit
    app.kubernetes.io/version: "2.31.12.20231011"
    app.kubernetes.io/managed-by: Helm
    make: ksh