apiVersion: v1
kind: Service
metadata:
  labels:
    helm.sh/chart: aws-for-fluent-bit-0.1.31
    app.kubernetes.io/name: aws-for-fluent-bit
    app.kubernetes.io/instance: aws-for-fluent-bit
    app.kubernetes.io/version: "2.31.12.20231011"
    app.kubernetes.io/managed-by: Helm
  name: aws-for-fluent-bit
  namespace: logging
spec:
  ports:
  - name: monitor-agent
    port: 2020
    protocol: TCP
    targetPort: 2020
  selector:
    app.kubernetes.io/name: aws-for-fluent-bit
    app.kubernetes.io/instance: aws-for-fluent-bit
  sessionAffinity: None
  type: ClusterIP