apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flentbit-role
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
  - apiGroups: [""]
    resources:
      - namespaces
      - pods
      - pods/logs
    verbs: ["get", "list", "watch"]
  
#ns, pod, pods/log에 대한 get list watch를 허용하는 cluster role
#metrics라는 경로에 대해서는 get 리소스 허용, https://arisu1000.tistory.com/27848